apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: orchestrator-saga-ns
data:
  KAFKA_LISTENERS: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092"
  KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-svc.orchestrator-saga-ns.svc.cluster.local:29092,EXTERNAL://kafka-svc.orchestrator-saga-ns.svc.cluster.local:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
  KAFKA_RESTART_ATTEMPTS: "10"
  KAFKA_RESTART_DELAY: "5"
  ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
