apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-cm
  namespace: orchestrator-saga-ns
data:
  KAFKA_BROKER: "kafka-svc.orchestrator-saga-ns.svc.cluster.local:9092"
  DB_HOST: "payment-db-svc.orchestrator-saga-ns.svc.cluster.local"
  DB_NAME: "payment-db"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  PUBLIC_KEY:
  ACCESS_TOKEN:
  API_URL: "http://payment-service-svc.orchestrator-saga-ns.svc.cluster.local"
  API_PORT: "8091"
