apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc-new
  namespace: orchestrator-saga-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  # Novo tamanho
