apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: orchestrator-saga-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: obsidiandynamics/kafka
        env:
        - name: KAFKA_LISTENERS
          value: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://kafka-svc.orchestrator-saga-ns.svc.cluster.local:29092,EXTERNAL://kafka-svc.orchestrator-saga-ns.svc.cluster.local:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        ports:
        - containerPort: 29092
          name: internal
        - containerPort: 9092
          name: external
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-pvc
