apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-dp
  namespace: orchestrator-saga-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: luankenzley/payment-service
        envFrom:
        - configMapRef:
            name: payment-service-cm
        ports:
        - containerPort: 8091
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
