apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-console
  namespace: orchestrator-saga-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-console
  template:
    metadata:
      labels:
        app: redpanda-console
    spec:
      containers:
      - name: redpanda-console
        image: docker.redpanda.com/vectorized/console:latest
        command: ["/bin/sh", "-c", "echo \"$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"]
        env:
        - name: CONFIG_FILEPATH
          value: /tmp/config.yml
        - name: CONSOLE_CONFIG_FILE
          valueFrom:
            configMapKeyRef:
              name: redpanda-console-config
              key: CONSOLE_CONFIG_FILE
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
