apiVersion: v1
kind: Service
metadata:
  name: inventory-service-svc
  namespace: orchestrator-saga-ns
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
  - port: 8092
    targetPort: 8092
    protocol: TCP
