apiVersion: v1
kind: Service
metadata:
  name: kitchen-db-svc
  namespace: orchestrator-saga-ns
spec:
  type: ClusterIP
  selector:
    app: kitchen-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
