apiVersion: v1
kind: Service
metadata:
  name: kitchen-service-svc
  namespace: orchestrator-saga-ns
spec:
  type: ClusterIP
  selector:
    app: kitchen-service
  ports:
  - port: 8093
    targetPort: 8093
    protocol: TCP
