apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service-svc
  namespace: orchestrator-saga-ns
spec:
  type: ClusterIP
  selector:
    app: orchestrator-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
