apiVersion: v1
kind: Service
metadata:
  name: order-db-svc
  namespace: orchestrator-saga-ns
spec:
  type: ClusterIP
  selector:
    app: order-db
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
