apiVersion: v1
kind: Service
metadata:
  name: order-service-svc
  namespace: orchestrator-saga-ns
spec:
  type: NodePort
  selector:
    app: order-service
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
