apiVersion: v1
kind: Service
metadata:
  name: payment-db-svc
  namespace: orchestrator-saga-ns
spec:
  type: ClusterIP
  selector:
    app: payment-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
