apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
  namespace: orchestrator-saga-ns
spec:
  type: NodePort
  selector:
    app: payment-service
  ports:
  - port: 8091
    targetPort: 8091
    nodePort: 30091
    protocol: TCP
