apiVersion: v1
kind: Service
metadata:
  name: product-validation-service-svc
  namespace: orchestrator-saga-ns
spec:
  type: NodePort
  selector:
    app: product-service-validation
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30090
    protocol: TCP
