apiVersion: v1
kind: Service
metadata:
  name: redpanda-console-svc
  namespace: orchestrator-saga-ns
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: redpanda-console
