apiVersion: v1
kind: ConfigMap
metadata:
  name: redpanda-console-config
  namespace: orchestrator-saga-ns
data:
  CONSOLE_CONFIG_FILE: |
    kafka:
      brokers:
        - "kafka-svc.orchestrator-saga-ns.svc.cluster.local:29092"